apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-client
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: simple-client
  targetCPUUtilizationPercentage: 80